//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.18 at 12:23:11 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.lucid.com/plans", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.lucid.subscription.jaxb;
