/**
 * All Rights Reserved. Private and Confidential. May not be disclosed without permission.
 */
package com.lucid.payment.data;

import com.lucid.core.vo.BaseVO;

/**
 * @author sgutti
 * @date 04-May-2023 11:00:23 pm
 */
public class GtwyCustomerProfileVO extends BaseVO {
  // --------------------------------------------------------------- Constants
  private static final long serialVersionUID = -1905180848473670296L;

  // --------------------------------------------------------- Class Variables
  // ----------------------------------------------------- Static Initializers
  // ------------------------------------------------------ Instance Variables
  private String gtwyCustomerProfileID;
  private String email;
  // PayPal, Strip, etc
  private String gtwyID;

  // This is id generated by the payment gateway when customer saves a payment
  // method is saved
  private String gtwyCustomerID;

  private Long subscriptionID;

  private String customerIPAddress;

  // ONE-TIME, RECURRING
  private String chargeType;

  // ------------------------------------------------------------ Constructors
  /**
   * Create a new <code>GtwyCustomerProfileVO</code>
   */
  public GtwyCustomerProfileVO() {
    super();
  }

  // ---------------------------------------------------------- Public Methods
  /**
   * @return Returns the gtwyCustomerProfileID.
   */
  public String getGtwyCustomerProfileID() {
    return gtwyCustomerProfileID;
  }

  /**
   * @param gtwyCustomerProfileID The gtwyCustomerProfileID to set.
   */
  public void setGtwyCustomerProfileID(String gtwyCustomerProfileID) {
    this.gtwyCustomerProfileID = gtwyCustomerProfileID;
  }

  /**
   * @return Returns the email.
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email The email to set.
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return Returns the gtwyID.
   */
  public String getGtwyID() {
    return gtwyID;
  }

  /**
   * @param gtwyID The gtwyID to set.
   */
  public void setGtwyID(String gtwyID) {
    this.gtwyID = gtwyID;
  }

  /**
   * @return Returns the gtwyCustomerID.
   */
  public String getGtwyCustomerID() {
    return gtwyCustomerID;
  }

  /**
   * @param gtwyCustomerID The gtwyCustomerID to set.
   */
  public void setGtwyCustomerID(String gtwyCustomerID) {
    this.gtwyCustomerID = gtwyCustomerID;
  }

  /**
   * @return Returns the subscriptionID.
   */
  public Long getSubscriptionID() {
    return subscriptionID;
  }

  /**
   * @param subscriptionID The subscriptionID to set.
   */
  public void setSubscriptionID(Long subscriptionID) {
    this.subscriptionID = subscriptionID;
  }

  /**
   * @return Returns the customerIPAddress.
   */
  public String getCustomerIPAddress() {
    return customerIPAddress;
  }

  /**
   * @param customerIPAddress The customerIPAddress to set.
   */
  public void setCustomerIPAddress(String customerIPAddress) {
    this.customerIPAddress = customerIPAddress;
  }

  /**
   * @return Returns the chargeType.
   */
  public String getChargeType() {
    return chargeType;
  }

  /**
   * @param chargeType The chargeType to set.
   */
  public void setChargeType(String chargeType) {
    this.chargeType = chargeType;
  }
  // ------------------------------------------------------- Protected Methods
  // --------------------------------------------------------- Default Methods
  // --------------------------------------------------------- Private Methods
  // ---------------------------------------------------------- Static Methods
  // ----------------------------------------------------------- Inner Classes
}
