/**
 * All Rights Reserved. Private and Confidential. May not be disclosed without permission.
 */
package com.lucid.payment.data;

import com.lucid.core.vo.BaseVO;

/**
 * @author sgutti
 * @date 04-May-2023 11:26:39 pm
 */

public class GtwyCustomerPymntProfileVO extends BaseVO {
  // --------------------------------------------------------------- Constants
  private static final long serialVersionUID = 1113574383064950989L;
  // --------------------------------------------------------- Class Variables
  // ----------------------------------------------------- Static Initializers
  // ------------------------------------------------------ Instance Variables
  private String gtwyCustomerPymntProfileID;
  private String gtwyCustomerProfileID;
  // This is the payment profile id generated by the payment gateway for a
  // customer
  private String gtwyPymntProfileID;
  private String name;
  // Charge default to the payment profile
  private Boolean defaultPymntInd;
  // ACTIVE/EXPIRED/DELETED
  private Integer status;
  //
  private String last4Digits;

  // expiration date in encrypted formated
  private String expirationEncDt;

  // VISA/MASTER/JCB etc
  private String cardType;

  // CREDIT-CARD,DEBIT-CARD,BANK
  private String pymntMethodID;



  // ------------------------------------------------------------ Constructors
  /**
   * Create a new <code>CustomerPymntGtwyProfile</code>
   */
  public GtwyCustomerPymntProfileVO() {
    super();
  }

  // ---------------------------------------------------------- Public Methods
  /**
   * @return Returns the gtwyCustomerPymntProfileID.
   */
  public String getGtwyCustomerPymntProfileID() {
    return gtwyCustomerPymntProfileID;
  }



  /**
   * @param gtwyCustomerPymntProfileID The gtwyCustomerPymntProfileID to set.
   */
  public void setGtwyCustomerPymntProfileID(String gtwyCustomerPymntProfileID) {
    this.gtwyCustomerPymntProfileID = gtwyCustomerPymntProfileID;
  }



  /**
   * @return Returns the gtwyCustomerProfileID.
   */
  public String getGtwyCustomerProfileID() {
    return gtwyCustomerProfileID;
  }



  /**
   * @param gtwyCustomerProfileID The gtwyCustomerProfileID to set.
   */
  public void setGtwyCustomerProfileID(String gtwyCustomerProfileID) {
    this.gtwyCustomerProfileID = gtwyCustomerProfileID;
  }



  /**
   * @return Returns the gtwyPymntProfileID.
   */
  public String getGtwyPymntProfileID() {
    return gtwyPymntProfileID;
  }



  /**
   * @param gtwyPymntProfileID The gtwyPymntProfileID to set.
   */
  public void setGtwyPymntProfileID(String gtwyPymntProfileID) {
    this.gtwyPymntProfileID = gtwyPymntProfileID;
  }



  /**
   * @return Returns the name.
   */
  public String getName() {
    return name;
  }



  /**
   * @param name The name to set.
   */
  public void setName(String name) {
    this.name = name;
  }



  /**
   * @return Returns the defaultPymntInd.
   */
  public Boolean getDefaultPymntInd() {
    return defaultPymntInd;
  }



  /**
   * @param defaultPymntInd The defaultPymntInd to set.
   */
  public void setDefaultPymntInd(Boolean defaultPymntInd) {
    this.defaultPymntInd = defaultPymntInd;
  }



  /**
   * @return Returns the status.
   */
  public Integer getStatus() {
    return status;
  }



  /**
   * @param status The status to set.
   */
  public void setStatus(Integer status) {
    this.status = status;
  }



  /**
   * @return Returns the last4Digits.
   */
  public String getLast4Digits() {
    return last4Digits;
  }



  /**
   * @param last4Digits The last4Digits to set.
   */
  public void setLast4Digits(String last4Digits) {
    this.last4Digits = last4Digits;
  }



  /**
   * @return Returns the expirationEncDt.
   */
  public String getExpirationEncDt() {
    return expirationEncDt;
  }



  /**
   * @param expirationEncDt The expirationEncDt to set.
   */
  public void setExpirationEncDt(String expirationEncDt) {
    this.expirationEncDt = expirationEncDt;
  }



  /**
   * @return Returns the cardType.
   */
  public String getCardType() {
    return cardType;
  }



  /**
   * @param cardType The cardType to set.
   */
  public void setCardType(String cardType) {
    this.cardType = cardType;
  }



  /**
   * @return Returns the pymntMethodID.
   */
  public String getPymntMethodID() {
    return pymntMethodID;
  }



  /**
   * @param pymntMethodID The pymntMethodID to set.
   */
  public void setPymntMethodID(String pymntMethodID) {
    this.pymntMethodID = pymntMethodID;
  }

  // ------------------------------------------------------- Protected Methods
  // --------------------------------------------------------- Default Methods
  // --------------------------------------------------------- Private Methods
  // ---------------------------------------------------------- Static Methods
  // ----------------------------------------------------------- Inner Classes
}
