/**
 * All Rights Reserved. Private and Confidential. May not be disclosed without permission.
 */
package com.lucid.payment.entity;

import com.lucid.core.entity.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * @author sgutti
 * @date 04-May-2023 11:26:39 pm
 */
@Entity
@Table(name = GtwyCustomerPymntProfile.TABLE_NAME)
public class GtwyCustomerPymntProfile extends BaseEntity {
  // --------------------------------------------------------------- Constants
  private static final long serialVersionUID = 1113574383064950989L;
  public static final String TABLE_NAME = "gtwy_customer_pymnt_profile";
  // --------------------------------------------------------- Class Variables
  // ----------------------------------------------------- Static Initializers
  // ------------------------------------------------------ Instance Variables

  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  @Column(name = "gtwy_customer_pymnt_profile_id", nullable = false, length = 75)
  private String gtwyCustomerPymntProfileID;

  @Column(name = "gtwy_customer_profile_id", nullable = false, length = 75)
  private String gtwyCustomerProfileID;

  // This is the payment profile id generated by the payment gateway for a
  // customer
  @Column(name = "gtwy_pymnt_profile_id", nullable = false, length = 100)
  private String gtwyPymntProfileID;


  @Column(name = "name", nullable = false, length = 100)
  private String name;

  // Charge default to the payment profile
  @Column(name = "default_pymnt_ind", nullable = false)
  private Boolean defaultPymntInd;

  // ACTIVE/EXPIRED/DELETED
  @Column(name = "status", nullable = false)
  private Integer status;

  //
  @Column(name = "last_4digits", nullable = false, length = 100)
  private String last4Digits;

  // expiration date in encrypted formated
  @Column(name = "expiration_enc_dt", nullable = true, length = 100)
  private String expirationEncDt;

  // VISA/MASTER/JCB etc
  @Column(name = "card_type", nullable = true, length = 25)
  private String cardType;

  // CREDIT-CARD,DEBIT-CARD,BANK
  @Column(name = "pymnt_method_id", nullable = false, length = 75)
  private String pymntMethodID;

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "gtwy_customer_profile_id", nullable = false, insertable = false,
      updatable = false)
  private GtwyCustomerProfile gtwyCustomerProfile;

  // ------------------------------------------------------------ Constructors
  /**
   * Create a new <code>CustomerPymntGtwyProfile</code>
   */
  public GtwyCustomerPymntProfile() {
    super();
  }
  // ---------------------------------------------------------- Public Methods

  /**
   * @return Returns the gtwyCustomerPymntProfileID.
   */
  public String getGtwyCustomerPymntProfileID() {
    return gtwyCustomerPymntProfileID;
  }

  /**
   * @param gtwyCustomerPymntProfileID The gtwyCustomerPymntProfileID to set.
   */
  public void setGtwyCustomerPymntProfileID(String gtwyCustomerPymntProfileID) {
    this.gtwyCustomerPymntProfileID = gtwyCustomerPymntProfileID;
  }

  /**
   * @return Returns the gtwyCustomerProfileID.
   */
  public String getGtwyCustomerProfileID() {
    return gtwyCustomerProfileID;
  }

  /**
   * @param gtwyCustomerProfileID The gtwyCustomerProfileID to set.
   */
  public void setGtwyCustomerProfileID(String gtwyCustomerProfileID) {
    this.gtwyCustomerProfileID = gtwyCustomerProfileID;
  }

  /**
   * @return Returns the gtwyPymntProfileID.
   */
  public String getGtwyPymntProfileID() {
    return gtwyPymntProfileID;
  }

  /**
   * @param gtwyPymntProfileID The gtwyPymntProfileID to set.
   */
  public void setGtwyPymntProfileID(String gtwyPymntProfileID) {
    this.gtwyPymntProfileID = gtwyPymntProfileID;
  }

  /**
   * @return Returns the name.
   */
  public String getName() {
    return name;
  }

  /**
   * @param name The name to set.
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return Returns the defaultPymntInd.
   */
  public Boolean getDefaultPymntInd() {
    return defaultPymntInd;
  }

  /**
   * @param defaultPymntInd The defaultPymntInd to set.
   */
  public void setDefaultPymntInd(Boolean defaultPymntInd) {
    this.defaultPymntInd = defaultPymntInd;
  }

  /**
   * @return Returns the status.
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * @param status The status to set.
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * @return Returns the last4Digits.
   */
  public String getLast4Digits() {
    return last4Digits;
  }

  /**
   * @param last4Digits The last4Digits to set.
   */
  public void setLast4Digits(String last4Digits) {
    this.last4Digits = last4Digits;
  }

  /**
   * @return Returns the expirationEncDt.
   */
  public String getExpirationEncDt() {
    return expirationEncDt;
  }

  /**
   * @param expirationEncDt The expirationEncDt to set.
   */
  public void setExpirationEncDt(String expirationEncDt) {
    this.expirationEncDt = expirationEncDt;
  }

  /**
   * @return Returns the pymntMethodID.
   */
  public String getPymntMethodID() {
    return pymntMethodID;
  }

  /**
   * @param pymntMethodID The pymntMethodID to set.
   */
  public void setPymntMethodID(String pymntMethodID) {
    this.pymntMethodID = pymntMethodID;
  }

  /**
   * @return Returns the gtwyCustomerProfile.
   */
  public GtwyCustomerProfile getGtwyCustomerProfile() {
    return gtwyCustomerProfile;
  }

  /**
   * @param gtwyCustomerProfile The gtwyCustomerProfile to set.
   */
  public void setGtwyCustomerProfile(GtwyCustomerProfile gtwyCustomerProfile) {
    this.gtwyCustomerProfile = gtwyCustomerProfile;
  }

  // ------------------------------------------------------- Protected Methods
  // --------------------------------------------------------- Default Methods
  // --------------------------------------------------------- Private Methods
  // ---------------------------------------------------------- Static Methods
  // ----------------------------------------------------------- Inner Classes
}
