/**
 * All Rights Reserved. Private and Confidential. May not be disclosed without permission.
 */
package com.lucid.payment.entity;

import com.lucid.core.entity.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * @author sgutti
 * @date 04-May-2023 11:00:23 pm
 */
@Entity
@Table(name = GtwyCustomerProfile.TABLE_NAME)
public class GtwyCustomerProfile extends AuditableEntity {
  // --------------------------------------------------------------- Constants
  private static final long serialVersionUID = -1905180848473670296L;
  public static final String TABLE_NAME = "gtwy_customer_profile";
  // --------------------------------------------------------- Class Variables
  // ----------------------------------------------------- Static Initializers
  // ------------------------------------------------------ Instance Variables
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  @Column(name = "gtwy_customer_profile_id", nullable = false, length = 75)
  private String gtwyCustomerProfileID;

  @Column(name = "email", nullable = false, length = 200)
  private String email;

  // PayPal, Strip, etc
  @Column(name = "gtwy_id", nullable = false, length = 25)
  private String gtwyID;

  // This is id generated by the payment gateway when customer saves a payment
  // method is saved
  @Column(name = "gtwy_customer_id", nullable = false, length = 100)
  private String gtwyCustomerID;

  @Column(name = "subscription_id", nullable = false)
  private Long subscriptionID;

  @Column(name = "customer_ipaddress", nullable = false, length = 45)
  private String customerIPAddress;

  // ONE-TIME, RECURRING
  @Column(name = "charge_type", nullable = false, length = 25)
  private String chargeType;

  // ------------------------------------------------------------ Constructors
  /**
   * Create a new <code>GtwyCustomerProfileVO</code>
   */
  public GtwyCustomerProfile() {
    super();
  }

  // ---------------------------------------------------------- Public Methods
  /**
   * @return Returns the gtwyCustomerProfileID.
   */
  public String getGtwyCustomerProfileID() {
    return gtwyCustomerProfileID;
  }

  /**
   * @param gtwyCustomerProfileID The gtwyCustomerProfileID to set.
   */
  public void setGtwyCustomerProfileID(String gtwyCustomerProfileID) {
    this.gtwyCustomerProfileID = gtwyCustomerProfileID;
  }

  /**
   * @return Returns the email.
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email The email to set.
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return Returns the gtwyID.
   */
  public String getGtwyID() {
    return gtwyID;
  }

  /**
   * @param gtwyID The gtwyID to set.
   */
  public void setGtwyID(String gtwyID) {
    this.gtwyID = gtwyID;
  }

  /**
   * @return Returns the gtwyCustomerID.
   */
  public String getGtwyCustomerID() {
    return gtwyCustomerID;
  }

  /**
   * @param gtwyCustomerID The gtwyCustomerID to set.
   */
  public void setGtwyCustomerID(String gtwyCustomerID) {
    this.gtwyCustomerID = gtwyCustomerID;
  }

  /**
   * @return Returns the subscriptionID.
   */
  public Long getSubscriptionID() {
    return subscriptionID;
  }

  /**
   * @param subscriptionID The subscriptionID to set.
   */
  public void setSubscriptionID(Long subscriptionID) {
    this.subscriptionID = subscriptionID;
  }

  /**
   * @return Returns the customerIPAddress.
   */
  public String getCustomerIPAddress() {
    return customerIPAddress;
  }

  /**
   * @param customerIPAddress The customerIPAddress to set.
   */
  public void setCustomerIPAddress(String customerIPAddress) {
    this.customerIPAddress = customerIPAddress;
  }

  /**
   * @return Returns the chargeType.
   */
  public String getChargeType() {
    return chargeType;
  }

  /**
   * @param chargeType The chargeType to set.
   */
  public void setChargeType(String chargeType) {
    this.chargeType = chargeType;
  }
  // ------------------------------------------------------- Protected Methods
  // --------------------------------------------------------- Default Methods
  // --------------------------------------------------------- Private Methods
  // ---------------------------------------------------------- Static Methods
  // ----------------------------------------------------------- Inner Classes
}
